title: DS Serve
url: https://infini-gram.io
baseurl: ""
header_pages:
  - demo.md
  - API_DOCUMENTATION.md
  - VOTES_DOCUMENTATION.md
  - code.md
  - paper.md

theme: minima
plugins:
  - jekyll-redirect-from
