title: DS Serve
url: https://berkeley-large-rag.github.io
baseurl: /RAG-DS-Serve
header_pages:
  - API_DOCUMENTATION.md
  - VOTES_DOCUMENTATION.md
  - code.md
  - paper.md

theme: minima
plugins:
  - jekyll-redirect-from
